---
apiVersion: v1
kind: application
metadata:
  name: devtest.drone_stabilization
  commType: http
spec:
  services:
    - serviceName: ms-drone_stabilization
      components:
        - componentName: drone_stabilization
          imageType: docker
          imageName: drone_stabilization
          httpPort: 3000
          interfaces:
            - interfaceName: dummy-api
              interfaceType: http
              upstreamPath: /dummy-api
              visiblity: internal
              accessList:
                - app@client
            - interfaceName: listener
              interfaceType: network
              interfacePort: 10000
              scheme: udp
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
